### ISSUE TITLE
reproducibility package feedback

### ISSUE THREAD

**Issue by wsavran** [bayonato89/Reproducibility-hybrids#1]
hi @bayonato89, the reproducibility runs smoothly on my computer, and is very easy to use. i was able to copy-paste the instructions into my terminal and they ran without error. nice job!

i have a couple of comments here that would help to improve the reproducibility package. 

1. the code should provide more output to help the user understand what is happening. the code looks derived from a jupyter notebook where the output probably happened inline. this is probably also a comment about the lack of verbosity in pycsep, but can be included in the ```reproducibility_hybrids.py``` script as well.
2. the function on line 147 ```query_comcat``` performs a live query of the catalog and can be subject to change. i would suggest that you obtain a version of this catalog and include it in the downloaded files from Zenodo. you can use the ```write_ascii``` and ```load_ascii``` functions to do this.

**Comment by wsavran** [comment]
follow up, i'd suggest to rename the files ```./exepcted_output/paper figures``` to ```./expected_output/README``` and ```./output/output figures``` to ```./expected_output/README```.  this might not be the best name, but i think at least we should remove the spaces.

**Comment by bayonato89** [comment]
Hi @wsavran, thank you very much for your valuable comments. I agree with all of them and have already made the corresponding changes. In particular, I documented the code to help the user know what is going on and added the earthquake catalog to the data folder. Also, I renamed those files as you suggested.
